file_format: "1"
id: hutoblev3
name: hutoblev3
type: shield
url: https://github.com/VincentHuto/hutoblev3
requires: [seeeduino_xiao_ble]
features:
  - keys
siblings:
  - hutoblev3_left
  - hutoblev3_right
