file_format: "1"
id: hutoblev1a
name: hutoblev1a
type: shield
url: https://github.com/VincentHuto/hutoble
requires: [seeeduino_xiao_ble]
features:
  - keys
siblings:
  - hutoblev1a_left
  - hutoblev1a_right
