file_format: "1"
id: hutoblev4
name: hutoblev4
type: shield
url: https://github.com/VincentHuto/hutoblev4
requires: [seeeduino_xiao_ble]
features:
  - keys
siblings:
  - hutoblev4_left
  - hutoblev4_right
